---

- name: check for version
  fail: msg="ERROR - 'java_version' is required."
  when: java_version is not defined

- include: install.yml

- include: extra_certs.yml jdk_cert_var="{{ item }}"
  with_items: "{{ java_extra_certs }}"
